### ISSUE TITLE
Support older android versions?

### ISSUE THREAD

**Issue by fegl84** [afollestad/material-camera#108]
- [x ] I have verified there are no duplicate active or recent bugs, questions, or requests
- [x ] I have verified that I am using the latest version of Material Camera.
- [x ] I have given my issue a non-generic title.

###### Include the following:
 - Material Camera version: `0.4.1`
 - Device OS version: `4.3`
 - Device Manufacturer: `Sony`
 - Device Name: `Xperia SP`

I've a problem use material-camera with older Android-Version. Does material-camera not support in older android versions?

```logcat
E/App: java.lang.RuntimeException: Unable to start activity ComponentInfo{de.heinekingmedia.stashcat/com.afollestad.materialcamera.CaptureActivity}: android.content.res.Resources$NotFoundException: File res/drawable/mcam_camera_rear.xml from drawable resource ID #0x7f0200a3
                                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2266)
                                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2316)
                                                                     at android.app.ActivityThread.access$600(ActivityThread.java:150)
                                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1298)
                                                                     at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                     at android.os.Looper.loop(Looper.java:213)
                                                                     at android.app.ActivityThread.main(ActivityThread.java:5225)
                                                                     at java.lang.reflect.Method.invokeNative(Native Method)
                                                                     at java.lang.reflect.Method.invoke(Method.java:525)
                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:741)
                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:557)
                                                                     at dalvik.system.NativeStart.main(Native Method)
                                                                  Caused by: android.content.res.Resources$NotFoundException: File res/drawable/mcam_camera_rear.xml from drawable resource ID #0x7f0200a3
                                                                     at android.content.res.Resources.loadDrawable(Resources.java:2103)
                                                                     at android.content.res.Resources.getDrawable(Resources.java:702)
                                                                     at android.support.v7.widget.ResourcesWrapper.getDrawable(ResourcesWrapper.java:128)
                                                                     at android.support.v7.widget.TintResources.getDrawable(TintResources.java:45)
                                                                     at android.support.v4.content.ContextCompat.getDrawable(ContextCompat.java:346)
                                                                     at com.afollestad.materialcamera.internal.BaseCameraFragment.setImageRes(BaseCameraFragment.java:92)
                                                                     at com.afollestad.materialcamera.internal.BaseCameraFragment.onViewCreated(BaseCameraFragment.java:110)
                                                                     at com.afollestad.materialcamera.internal.CameraFragment.onViewCreated(CameraFragment.java:101)
                                                                     at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:903)
                                                                     at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1061)
                                                                     at android.app.BackStackRecord.run(BackStackRecord.java:682)
                                                                     at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1443)
                                                                     at android.app.Activity.performStart(Activity.java:5142)
                                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2239)
                                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2316) 
                                                                     at android.app.ActivityThread.access$600(ActivityThread.java:150) 
                                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1298) 
                                                                     at android.os.Handler.dispatchMessage(Handler.java:99) 
                                                                     at android.os.Looper.loop(Looper.java:213) 
                                                                     at android.app.ActivityThread.main(ActivityThread.java:5225) 
                                                                     at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                     at java.lang.reflect.Method.invoke(Method.java:525) 
                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:741) 
                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:557) 
                                                                     at dalvik.system.NativeStart.main(Native Method) 
                                                                  Caused by: org.xmlpull.v1.XmlPullParserException: Binary XML file line #1: invalid drawable tag vector
                                                                     at android.graphics.drawable.Drawable.createFromXmlInner(Drawable.java:925)
                                                                     at android.graphics.drawable.Drawable.createFromXml(Drawable.java:853)
                                                                     at android.content.res.Resources.loadDrawable(Resources.java:2099)
                                                                     at android.content.res.Resources.getDrawable(Resources.java:702) 
                                                                     at android.support.v7.widget.ResourcesWrapper.getDrawable(ResourcesWrapper.java:128) 
                                                                     at android.support.v7.widget.TintResources.getDrawable(TintResources.java:45) 
                                                                     at android.support.v4.content.ContextCompat.getDrawable(ContextCompat.java:346) 
                                                                     at com.afollestad.materialcamera.internal.BaseCameraFragment.setImageRes(BaseCameraFragment.java:92) 
                                                                     at com.afollestad.materialcamera.internal.BaseCameraFragment.onViewCreated(BaseCameraFragment.java:110) 
                                                                     at com.afollestad.materialcamera.internal.CameraFragment.onViewCreated(CameraFragment.java:101) 
                                                                     at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:903) 
                                                                     at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1061) 
                                                                     at android.app.BackStackRecord.run(BackStackRecord.java:682) 
                                                                     at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1443) 
                                                                     at android.app.Activity.performStart(Activity.java:5142) 
                                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2239) 
                                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2316) 
                                                                     at android.app.ActivityThread.access$600(ActivityThread.java:150) 
                                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1298) 
                                                                     at android.os.Handler.dispatchMessage(Handler.java:99) 
                                                                     at android.os.Looper.loop(Looper.java:213) 
                                                                     at android.app.ActivityThread.main(ActivityThread.java:5225) 
                                                                     at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                     at java.lang.reflect.Method.invoke(Method.java:525) 
                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:741) 
                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:557) 
                                                                     at dalvik.system.NativeStart.main(Native Method) 
```

 
###### Reproduction Steps
1. start camera

###### Expected Result
1. camera starts
2. ready to take movie or picture

###### Actual Result
1. camera starts 
2. crash

**Comment by afollestad** [comment]
```gradle
 android {  
   ...
   defaultConfig {  
     vectorDrawables.useSupportLibrary = true  
    }  
 }  
```
