### ISSUE TITLE
CameraDevice was already closed

### ISSUE THREAD

**Issue by toidv** [afollestad/material-camera#138]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests
- [x] I have verified that I am using the latest version of Material Camera.
- [x] I have given my issue a non-generic title.

###### Include the following:
 - Material Camera version: `0.4.1`
 - Device OS version: `6.0.1`
 - Device Manufacturer: `LG`
 - Device Name: `Nexus 5`

```java
MaterialCamera camera = new MaterialCamera(activity)
                    .showPortraitWarning(true)
                    .allowRetry(true)
                    .defaultToFrontFacing(true)
                    .countdownSeconds(30);

            if (isWriteExternalStoragePermission) {
                File saveDir = new File(Environment.getExternalStorageDirectory(), "Inploi");
                saveDir.mkdirs();
                camera.saveDir(saveDir);
            }
            camera.start(CAMERA_RQ);
```
 
###### Reproduction Steps

1. Open material camera
2. Swipe front to rear camera
3. Crash happen

```
java.lang.IllegalStateException: CameraDevice was already closed
at android.hardware.camera2.impl.CameraDeviceImpl.checkIfCameraClosedOrInError(CameraDeviceImpl.java:1997)
at android.hardware.camera2.impl.CameraDeviceImpl.submitCaptureRequest(CameraDeviceImpl.java:844)
at android.hardware.camera2.impl.CameraDeviceImpl.setRepeatingRequest(CameraDeviceImpl.java:899)
at android.hardware.camera2.impl.CameraCaptureSessionImpl.setRepeatingRequest(CameraCaptureSessionImpl.java:236)
at com.afollestad.materialcamera.internal.Camera2Fragment.onPreferencesUpdated(Camera2Fragment.java:678)
at com.afollestad.materialcamera.internal.BaseCameraFragment.invalidateFlash(BaseCameraFragment.java:415)
at com.afollestad.materialcamera.internal.BaseCameraFragment.onFlashModesLoaded(BaseCameraFragment.java:158)
at com.afollestad.materialcamera.internal.Camera2Fragment.openCamera(Camera2Fragment.java:631)
at com.afollestad.materialcamera.internal.BaseCameraFragment.onClick(BaseCameraFragment.java:380)
at com.afollestad.materialcamera.internal.Camera2Fragment.onClick(Camera2Fragment.java:73)
```

**Comment by afollestad** [comment]
Since I haven't ever had this problem on Nexus or Pixel devices, I will assume it was a one time thing.
