### ISSUE TITLE
Crash on Marshmallow

### ISSUE THREAD

**Issue by vikas442** [afollestad/material-camera#206]
- [ ] I have verified there are no duplicate active or recent bugs, questions, or requests
- [ ] I have verified that I am using the latest version of Material Camera.
- [ ] I have given my issue a non-generic title.

###### Include the following:
 - Material Camera version: `0.4.4`
 - Device OS version: `6.0.1`
 - Device Manufacturer: `LG`
 - Device Name: `Nexus 5`

Mentioned below is the stack trace:

java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.String
                                                                       at com.afollestad.materialcamera.internal.Camera2Fragment.openCamera(Camera2Fragment.java:484)
                                                                       at com.afollestad.materialcamera.internal.Camera2Fragment$1.onSurfaceTextureAvailable(Camera2Fragment.java:97)
                                                                       at android.view.TextureView.getHardwareLayer(TextureView.java:368)
                                                                       at android.view.View.updateDisplayListIfDirty(View.java:15157)
                                                                       at android.view.View.draw(View.java:15954)
                                                                       at android.view.ViewGroup.drawChild(ViewGroup.java:3609)
                                                                       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3399)
                                                                       at android.view.View.updateDisplayListIfDirty(View.java:15175)
                                                                       at android.view.View.draw(View.java:15954)
                                                                       at android.view.ViewGroup.drawChild(ViewGroup.java:3609)
                                                                       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3399)
                                                                       at android.view.View.draw(View.java:16187)
                                                                       at android.view.View.updateDisplayListIfDirty(View.java:15180)
                                                                       at android.view.View.draw(View.java:15954)
                                                                       at android.view.ViewGroup.drawChild(ViewGroup.java:3609)
                                                                       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3399)
                                                                       at android.view.View.draw(View.java:16187)
                                                                       at android.view.View.updateDisplayListIfDirty(View.java:15180)
                                                                       at android.view.View.draw(View.java:15954)
                                                                       at android.view.ViewGroup.drawChild(ViewGroup.java:3609)
                                                                       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3399)
                                                                       at android.view.View.updateDisplayListIfDirty(View.java:15175)
                                                                       at android.view.View.draw(View.java:15954)
                                                                       at android.view.ViewGroup.drawChild(ViewGroup.java:3609)
                                                                       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3399)
                                                                       at android.view.View.updateDisplayListIfDirty(View.java:15175)
                                                                       at android.view.View.draw(View.java:15954)
                                                                       at android.view.ViewGroup.drawChild(ViewGroup.java:3609)
                                                                       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3399)
                                                                       at android.view.View.updateDisplayListIfDirty(View.java:15175)
                                                                       at android.view.View.draw(View.java:15954)
                                                                       at android.view.ViewGroup.drawChild(ViewGroup.java:3609)
                                                                       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3399)
                                                                       at android.view.View.updateDisplayListIfDirty(View.java:15175)
                                                                       at android.view.View.draw(View.java:15954)
                                                                       at android.view.ViewGroup.drawChild(ViewGroup.java:3609)
                                                                       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3399)
                                                                       at android.view.View.draw(View.java:16187)
                                                                       at com.android.internal.policy.PhoneWindow$DecorView.draw(PhoneWindow.java:2690)
                                                                       at android.view.View.updateDisplayListIfDirty(View.java:15180)
                                                                       at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:281)
                                                                       at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:287)
                                                                       at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:322)
                                                                       at android.view.ViewRootImpl.draw(ViewRootImpl.java:2615)
                                                                       at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2434)
                                                                       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2067)
                                                                       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1107)
                                                                       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6013)
                                                                       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:858)
                                                                       at android.view.Choreographer.doCallbacks(Choreographer.java:670)
                                                                       at android.view.Choreographer.doFrame(Choreographer.java:606)
                                                                       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
                                                                       at android.os.Handler.handleCallback(Handler.java:739)
                                                                       at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                       at android.os.Looper.loop(Looper.java:148)
                                                                       at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by sebamena** [comment]
I have the same issue in Huawei Mate 9 Lite Android 7.0.
