### ISSUE TITLE
Camera device has encountered a fatal error, please try again

### ISSUE THREAD

**Issue by ganshenml** [afollestad/material-camera#213]
- [ ] I have verified there are no duplicate active or recent bugs, questions, or requests
- [ ] I have verified that I am using the latest version of Material Camera.
- [ ] I have given my issue a non-generic title.

###### Include the following:
 - Material Camera version: `0.4.4`
 - Device OS version: `7.0`
 - Device Manufacturer: `Huawei`
 - Device Name: `P10`

Here is the log:
`
I/CameraManagerGlobal: Connecting to camera service
I/HwMediaPermWrapper: confirmCameraPermission, blocked:false
W/System.err: java.lang.Exception: Camera device has encountered a fatal error, please try again.
W/System.err:     at com.afollestad.materialcamera.internal.Camera2Fragment$2.onError(Camera2Fragment.java:167)
W/System.err:     at android.hardware.camera2.impl.CameraDeviceImpl$CameraDeviceCallbacks$1.run(CameraDeviceImpl.java:1651)
W/System.err:     at android.os.Handler.handleCallback(Handler.java:761)
W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:98)
W/System.err:     at android.os.Looper.loop(Looper.java:156)
W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:6577)
W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:942)
W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832)
`

**Comment by yukimon** [comment]
try  this 
 .forceCamera1()
