### ISSUE TITLE
"autoFocus failed" issue on Sony Z3

### ISSUE THREAD

**Issue by ruha9005** [afollestad/material-camera#31]
```Gradle
FATAL EXCEPTION: main
Process: ************, PID: 15109
java.lang.RuntimeException: autoFocus failed 
at android.hardware.Camera.native_autoFocus(Native Method) 
at android.hardware.Camera.autoFocus(Camera.java:1299)
at com.afollestad.materialcamera.internal.CameraFragment.onClick(CameraFragment.java:118)
at android.view.View.performClick(View.java:4856)
...
```

on few fast clicks on screen when recording

**Comment by afollestad** [comment]
https://github.com/afollestad/material-camera/releases/tag/0.2.2

**Comment by afollestad** [comment]
https://github.com/afollestad/material-camera/releases/tag/0.2.4
